ZomSelect({PrimType="Edge", WorkingSet="Visible", Select=true, All=true})
ZomWeld({PrimType="Edge", WorkingSet="Visible&UnLocked", Mode="AcrossIslands", BothSides=true})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={Box={ActiveEdges={ "XPYP", "XPZP", "XPYM", "XPZM", "YPZP", "YMZP", "YMZM", "YPZM", "XMYP", "XMZP", "XMYM", "XMZM" }}, HandleCutter=true}})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={Box={ActiveEdges={ "XPYP", "XPZP", "XPYM", "XPZM", "YPZP", "YMZP", "YMZM", "YPZM", "XMYP", "XMZP", "XMYM", "XMZM" }}, HandleCutter=true, StoreCoordsUVW=true, FlatteningMode=2}})
ZomCut({PrimType="Edge", WorkingSet="Visible&UnLocked"})
ZomLoad({Data={CoordsUVWInternalPath="#Mesh.Tmp.AutoSelect.UVW "}})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={Box={ActiveEdges={ "XPYP", "XPZP", "XPYM", "XPZM", "YPZP", "YMZP", "YMZM", "YPZM", "XMYP", "XMZP", "XMYM", "XMZM" }}, HandleCutter=true, StoreCoordsUVW=true, FlatteningMode=2}})
ZomCut({PrimType="Edge", WorkingSet="Visible&UnLocked"})
ZomLoad({Data={CoordsUVWInternalPath="#Mesh.Tmp.AutoSelect.UVW "}})
ZomIslandGroups({Mode="DistributeInTilesByBBox", WorkingSet="Visible"})
ZomIslandGroups({Mode="DistributeTilesContent", WorkingSet="Visible&UnLocked", FreezeIslands=true, UseTileLocks=true, UseIslandLocks=true, GroupPaths={ "RootGroup" }})
ZomPack({WorkingSet="Visible", AuxGroup="RootGroup"})
