ZomSelect({PrimType="Edge", WorkingSet="Visible", Select=true, All=true})
ZomWeld({PrimType="Edge", WorkingSet="Visible&UnLocked", Mode="AcrossIslands", BothSides=true})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={Skeleton={Open=true, SegLevels={ 1, 2, 3}}, HandleCutter=true, QuadLoopCutter=true}})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={Skeleton={Open=true, SegLevels={ 1, 2, 3}}, HandleCutter=true, QuadLoopCutter=true, StoreCoordsUVW=true, FlatteningMode=0, FlatteningUnfoldParams={BorderIntersections=true, TriangleFlips=true}}})
ZomCut({PrimType="Edge", WorkingSet="Visible&UnLocked"})
ZomLoad({Data={CoordsUVWInternalPath="#Mesh.Tmp.AutoSelect.UVW "}})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={Skeleton={Open=true, SegLevels={ 1, 2, 3}}, HandleCutter=true, QuadLoopCutter=true, StoreCoordsUVW=true, FlatteningMode=0, FlatteningUnfoldParams={BorderIntersections=true, TriangleFlips=true}}})
ZomCut({PrimType="Edge", WorkingSet="Visible&UnLocked"})
ZomLoad({Data={CoordsUVWInternalPath="#Mesh.Tmp.AutoSelect.UVW "}})
ZomIslandGroups({Mode="DistributeInTilesByBBox", WorkingSet="Visible"})
ZomIslandGroups({Mode="DistributeTilesContent", WorkingSet="Visible&UnLocked", FreezeIslands=true, UseTileLocks=true, UseIslandLocks=true, GroupPaths={ "RootGroup" }})
ZomPack({WorkingSet="Visible", AuxGroup="RootGroup"})
