ZomSelect({PrimType="Edge", WorkingSet="Visible", Select=true, All=true})
ZomDeform({WorkingSet="Visible", PrimType="Edge", Geometrical="TransformIslandsByEdgePairs"})
ZomWeld({PrimType="Edge", WorkingSet="Visible&UnLocked", Mode="All"})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={SharpEdges={AngleMin=60}, PipesCutter=false, HandleCutter=true, QuadLoopCutter=true}, GeoNormals=true})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={SharpEdges={AngleMin=60}, PipesCutter=false, HandleCutter=true, QuadLoopCutter=true, StoreCoordsUVW=true, FlatteningMode=0, FlatteningUnfoldParams={BorderIntersections=true, TriangleFlips=true}}, GeoNormals=true})
ZomCut({PrimType="Edge", WorkingSet="Visible&UnLocked"})
ZomLoad({Data={CoordsUVWInternalPath="#Mesh.Tmp.AutoSelect.UVW "}})
ZomSelect({PrimType="Edge", WorkingSet="Visible&UnLocked", Select=true, ResetBefore=true, ProtectMapName="Protect", FilterIslandVisible=true, Auto={SharpEdges={AngleMin=60}, PipesCutter=false, HandleCutter=true, QuadLoopCutter=true, StoreCoordsUVW=true, FlatteningMode=0, FlatteningUnfoldParams={BorderIntersections=true, TriangleFlips=true}}, GeoNormals=true})
ZomCut({PrimType="Edge", WorkingSet="Visible&UnLocked"})
ZomLoad({Data={CoordsUVWInternalPath="#Mesh.Tmp.AutoSelect.UVW "}})
ZomIslandGroups({Mode="DistributeInTilesByBBox", WorkingSet="Visible"})
ZomIslandGroups({Mode="DistributeTilesContent", WorkingSet="Visible&UnLocked", FreezeIslands=true, UseTileLocks=true, UseIslandLocks=true, GroupPaths={ "RootGroup" }})
ZomPack({WorkingSet="Visible", AuxGroup="RootGroup"})
